name: pact-php

on:
  push: 
  pull_request:
  # Once on the first of the month at 06:00 UTC
  schedule:
    - cron: 0 6 1 * *

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  php-cs:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: [ '8.2' ]

    steps:
      - uses: actions/checkout@v4
        name: Checkout repository

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}

      - uses: ramsey/composer-install@v2
        with:
          dependency-versions: 'locked'

      - name: Code Style Analysis
        run: composer run lint

      - name: Static Code Analysis
        run: composer run static-code-analysis

  test:
    runs-on: ${{ matrix.operating-system }}
    needs:
      - php-cs
    strategy:
      fail-fast: false
      matrix:
        operating-system: [ ubuntu-latest, macos-latest, windows-latest ]
        php: [ '8.0', '8.1', '8.2' ]
        dependencies: [ 'lowest', 'locked' ]

    name: PHP ${{ matrix.php }} on ${{ matrix.operating-system }} with ${{ matrix.dependencies }} dependencies

    steps:
      - uses: actions/checkout@v4
        name: Checkout repository

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          extensions: openssl, sockets, curl, zip
          php-version: ${{ matrix.php }}

      - name: Composer install
        uses: ramsey/composer-install@v2
        with:
          dependency-versions: ${{ matrix.dependencies }}

      - name: Composer test
        run: composer test
